version: "3.3"
services:
  database:
    image: "mongo"
    ports:
      - "27017:27017"

  server:
    depends_on:
      - database
    build: .
    ports:
      - "4001:4001"
    environment:
      MONGO_URI: "database"
      MONGO_PORT: 27017
      MONGO_USER: ""
      MONGO_PASSWORD: ""
      MONGO_DATABASE: "DTS"

  app:
    build: ../SAB-GUI
    depends_on:
      - database
      - server
    ports:
      - "3000:3000"
    environment:
      CONNECTION_STRING: "server:4001"
