version: "3"
services:
  database:
    image: "mongo"
    ports:
      - "27017:27017"

  server:
    depends_on:
      - database
    build: .
    environment:
      MONGO_URI: database
      MONGO_PORT: 27017
      MONGO_USER: ""
      MONGO_PASSWORD: ""
      MONGO_DATABASE: "DTS"
    # command:
    #   - "./seed.sh"

  app:
    depends_on:
      - database
      - server
    build: ../SAB-GUI/.
    ports:
      - "3000:3000"
    environment:
      RAZZLE_CONNECTION_STRING: "server:4001"
      PORT: 3000
