openapi: 3.0.2
info:
  title: SAB-API
  description: API for viewing and managing office, appointment and biokit information
  version: 0.1.9

servers:
  - url: 'https://'
    description: Development server

paths:
  /locations:
    get:
      summary: Returns all locations
      responses:
